version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - npm run test
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: public